services:
  contract:
    build: .
    tty: true
    volumes:
      - .:/app
      - contract_node_modules:/app/node_modules
  redoc:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npx -y @redocly/cli@1.26.0 preview-docs openapi/todo.yaml -p 8082 -h 0.0.0.0"
    ports:
      - "8082:8082"
    volumes:
      - .:/app
volumes:
  contract_node_modules:
