name: spectral-lint
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
      - name: Report via reviewdog (PR checks)
        continue-on-error: true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx spectral lint openapi/todo.yaml -f sarif | reviewdog -f=sarif -name="Spectral" -reporter=github-pr-check -filter-mode=nofilter -fail-on-error=false || true
      - name: Run Spectral (fail on errors)
        run: npm run lint
